package aoc;/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.stream.Collectors;

public class App {
    private final List<Integer> input;

    public App(List<Integer> input) {
        this.input = input;
    }

    public Integer getSolutionPart1() {
        int result = 0;
        for (int i = 1; i < input.size(); i++) {
            if (input.get(i) > input.get(i - 1)) {
                result++;
            }
        }
        return result;
    }

    public Integer getSolutionPart2() {
        int result = 0;
        for (int i = 3; i < input.size(); i++) {

            int window1 = input.get(i - 1) + input.get(i - 2) + input.get(i-3);
            int window2 = input.get(i) + input.get(i - 1) + input.get(i - 2);

            if (window2 > window1) {
                result++;
            }
        }
        return result;
    }

    public static void main(String[] args) throws IOException {
        System.out.println("java");
        List<Integer> input = parseInput("input.txt");
        String part = System.getenv("part") == null ? "part1" : System.getenv("part");
        if (part.equals("part2"))
            System.out.println(new App(input).getSolutionPart2());
        else
            System.out.println(new App(input).getSolutionPart1());
    }

    private static List<Integer> parseInput(String filename) throws IOException {
        return Files.lines(Path.of(filename))
                .map(Integer::parseInt)
                .collect(Collectors.toList());
    }
}